// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWx5BIfGW24Kie2P1kYNllcSaY8Kog8GA',
    appId: '1:556347781394:android:399cc1109dd178c1fd03cb',
    messagingSenderId: '556347781394',
    projectId: 'bus-seat-reservation-49ef6',
    storageBucket: 'bus-seat-reservation-49ef6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqAjJmGiAAjno4oJZWkPtZD_i-ZA8RtIU',
    appId: '1:556347781394:ios:6df988abc3e09cabfd03cb',
    messagingSenderId: '556347781394',
    projectId: 'bus-seat-reservation-49ef6',
    storageBucket: 'bus-seat-reservation-49ef6.appspot.com',
    iosClientId: '556347781394-qbra51lavqc9r7oi1fonl2mouvsrn4bk.apps.googleusercontent.com',
    iosBundleId: 'com.example.busSeatBookingUser',
  );
}
